apiVersion: v1
kind: Service
metadata:
  name: demo-test-svc-production
  namespace: production
spec:
  selector:
    app: demo-test-production
  ports:
  - name: demo_ms
    port: 80
    targetPort: 80