apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-test-otel-config-production
  namespace: production
data:
  otel-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 127.0.0.1:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 25
      batch:
        timeout: 5s
        send_batch_size: 256
    exporters:
      awsxray:
        region: ap-southeast-1
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [awsxray]
      telemetry:
        logs:
          level: info
